BEGIN TRANSACTION;
CREATE TABLE categories(num INT, name VARCHAR(30), desc VARCHAR(100));
INSERT INTO "categories" VALUES(1,'tools','Coding and System Tools');
INSERT INTO "categories" VALUES(2,'affordances','Affordances');
INSERT INTO "categories" VALUES(3,'examples','Test, Benchmarking, and Example Code');
INSERT INTO "categories" VALUES(4,'toys','Toys and Games');
INSERT INTO "categories" VALUES(5,'algorithms','Working Algorithms and Implementations');
INSERT INTO "categories" VALUES(6,'other','Other');
CREATE TABLE "master"(intname VARCHAR(30), category VARCHAR(30), visname VARCHAR(30), attrib VARCHAR(100), language VARCHAR(30), langdetail VARCHAR(100));
INSERT INTO "master" VALUES('apply-license','tools','apply-license',NULL,'shell',NULL);
INSERT INTO "master" VALUES('favicon','tools','favicon',NULL,'shell',NULL);
INSERT INTO "master" VALUES('mkgit','tools','mkgit',NULL,'shell',NULL);
INSERT INTO "master" VALUES('parseargs','tools','ParseArgs',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('phonetic-code','tools','phonetic-code',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('sedit','tools','sedit',NULL,'shell',NULL);
INSERT INTO "master" VALUES('ziggurat','tools','Ziggurat',NULL,'c',NULL);
INSERT INTO "master" VALUES('browser-text','affordances','Browser-Text',NULL,'misc','shell and Nickle');
INSERT INTO "master" VALUES('ikiwiki-farm','affordances','ikiwiki-farm',NULL,'shell',NULL);
INSERT INTO "master" VALUES('exam-macros','affordances','exam-macros',NULL,'misc','m4 and LaTeX');
INSERT INTO "master" VALUES('page-mode','affordances','page-mode',NULL,'misc','Emacs lisp');
INSERT INTO "master" VALUES('concatmap','examples','concatMap',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('huffman','examples','Huffman',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('imcs','examples','IMCS',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('isize','examples','isize','with Mike Haertel','c',NULL);
INSERT INTO "master" VALUES('java-aux','examples','java-aux',NULL,'java',NULL);
INSERT INTO "master" VALUES('java-des','examples','java-DES',NULL,'java',NULL);
INSERT INTO "master" VALUES('popcount','examples','Popcount',NULL,'c',NULL);
INSERT INTO "master" VALUES('riviera','examples','Riviera','Julian Kongslie','haskell',NULL);
INSERT INTO "master" VALUES('rle','examples','RunList',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('stratify','examples','stratify',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('hypnomoire','toys','HypnoMoire',NULL,'java',NULL);
INSERT INTO "master" VALUES('raytracer','toys','Raytracer',NULL,'c','C++');
INSERT INTO "master" VALUES('skirmish','toys','skirmish','anonymous student','misc','Python');
INSERT INTO "master" VALUES('ttt','toys','TTT',NULL,'java',NULL);
INSERT INTO "master" VALUES('bmpf','algorithms','BMPF',NULL,'c',NULL);
INSERT INTO "master" VALUES('chortl','algorithms','Chortl','Julian Kongslie','haskell',NULL);
INSERT INTO "master" VALUES('simhash','algorithms','simhash',NULL,'c',NULL);
INSERT INTO "master" VALUES('thimk','algorithms','thimk',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('truelevel','algorithms','truelevel',NULL,'haskell',NULL);
INSERT INTO "master" VALUES('uothesis','other','UO-Thesis',NULL,'misc','LaTeX');
CREATE TABLE languages(num INT, name VARCHAR(30), desc VARCHAR(100));
INSERT INTO "languages" VALUES(1,'c','C and C++');
INSERT INTO "languages" VALUES(2,'haskell','Haskell');
INSERT INTO "languages" VALUES(3,'java','Java');
INSERT INTO "languages" VALUES(4,'shell','Shell Scripts');
INSERT INTO "languages" VALUES(5,'misc','Misc');
COMMIT;
