BEGIN TRANSACTION;
CREATE TABLE categories(num INT, name VARCHAR(30), desc VARCHAR(100));
INSERT INTO "categories" VALUES(1,'tools','Coding and System Tools');
INSERT INTO "categories" VALUES(2,'affordances','Affordances');
INSERT INTO "categories" VALUES(3,'examples','Test, Benchmarking, and Example Code');
INSERT INTO "categories" VALUES(4,'toys','Toys and Games');
INSERT INTO "categories" VALUES(5,'algorithms','Working Algorithms and Implementations');
INSERT INTO "categories" VALUES(6,'other','Other');
CREATE TABLE by_category(intname VARCHAR(30), category VARCHAR(30), visname VARCHAR(30), attrib VARCHAR(100));
INSERT INTO "by_category" VALUES('apply-license','tools','apply-license',NULL);
INSERT INTO "by_category" VALUES('favicon','tools','favicon',NULL);
INSERT INTO "by_category" VALUES('mkgit','tools','mkgit',NULL);
INSERT INTO "by_category" VALUES('parseargs','tools','ParseArgs',NULL);
INSERT INTO "by_category" VALUES('phonetic-code','tools','phonetic-code',NULL);
INSERT INTO "by_category" VALUES('sedit','tools','sedit',NULL);
INSERT INTO "by_category" VALUES('ziggurat','tools','Ziggurat',NULL);
INSERT INTO "by_category" VALUES('browser-text','affordances','Browser-Text',NULL);
INSERT INTO "by_category" VALUES('ikiwiki-farm','affordances','ikiwiki-farm',NULL);
INSERT INTO "by_category" VALUES('exam-macros','affordances','exam-macros',NULL);
INSERT INTO "by_category" VALUES('page-mode','affordances','page-mode',NULL);
INSERT INTO "by_category" VALUES('concatmap','examples','concatMap',NULL);
INSERT INTO "by_category" VALUES('huffman','examples','Huffman',NULL);
INSERT INTO "by_category" VALUES('imcs','examples','IMCS',NULL);
INSERT INTO "by_category" VALUES('isize','examples','isize','with Mike Haertel');
INSERT INTO "by_category" VALUES('java-aux','examples','java-aux',NULL);
INSERT INTO "by_category" VALUES('java-des','examples','java-DES',NULL);
INSERT INTO "by_category" VALUES('popcount','examples','Popcount',NULL);
INSERT INTO "by_category" VALUES('riviera','examples','Riviera','Julian Kongslie');
INSERT INTO "by_category" VALUES('rle','examples','RunList',NULL);
INSERT INTO "by_category" VALUES('stratify','examples','stratify',NULL);
INSERT INTO "by_category" VALUES('hypnomoire','toys','HypnoMoire',NULL);
INSERT INTO "by_category" VALUES('raytracer','toys','Raytracer',NULL);
INSERT INTO "by_category" VALUES('skirmish','toys','skirmish','anonymous student');
INSERT INTO "by_category" VALUES('ttt','toys','TTT',NULL);
INSERT INTO "by_category" VALUES('bmpf','algorithms','BMPF',NULL);
INSERT INTO "by_category" VALUES('chortl','algorithms','Chortl','Julian Kongslie');
INSERT INTO "by_category" VALUES('simhash','algorithms','simhash',NULL);
INSERT INTO "by_category" VALUES('thimk','algorithms','thimk',NULL);
INSERT INTO "by_category" VALUES('truelevel','algorithms','truelevel',NULL);
INSERT INTO "by_category" VALUES('uothesis','other','UO-Thesis',NULL);
CREATE TABLE by_language(intname VARCHAR(30), language VARCHAR(30), detail VARCHAR(100));
INSERT INTO "by_language" VALUES('bmpf','c',NULL);
INSERT INTO "by_language" VALUES('isize','c',NULL);
INSERT INTO "by_language" VALUES('popcount','c',NULL);
INSERT INTO "by_language" VALUES('raytracer','c','C++');
INSERT INTO "by_language" VALUES('simhash','c',NULL);
INSERT INTO "by_language" VALUES('ziggurat','c',NULL);
INSERT INTO "by_language" VALUES('chortl','haskell',NULL);
INSERT INTO "by_language" VALUES('concatmap','haskell',NULL);
INSERT INTO "by_language" VALUES('huffman','haskell',NULL);
INSERT INTO "by_language" VALUES('imcs','haskell',NULL);
INSERT INTO "by_language" VALUES('parseargs','haskell',NULL);
INSERT INTO "by_language" VALUES('phonetic-code','haskell',NULL);
INSERT INTO "by_language" VALUES('riviera','haskell',NULL);
INSERT INTO "by_language" VALUES('rle','haskell',NULL);
INSERT INTO "by_language" VALUES('stratify','haskell',NULL);
INSERT INTO "by_language" VALUES('thimk','haskell',NULL);
INSERT INTO "by_language" VALUES('truelevel','haskell',NULL);
INSERT INTO "by_language" VALUES('hypnomoire','java',NULL);
INSERT INTO "by_language" VALUES('java-aux','java',NULL);
INSERT INTO "by_language" VALUES('java-des','java',NULL);
INSERT INTO "by_language" VALUES('ttt','java',NULL);
INSERT INTO "by_language" VALUES('apply-license','shell',NULL);
INSERT INTO "by_language" VALUES('favicon','shell',NULL);
INSERT INTO "by_language" VALUES('ikiwiki-farm','shell',NULL);
INSERT INTO "by_language" VALUES('mkgit','shell',NULL);
INSERT INTO "by_language" VALUES('sedit','shell',NULL);
INSERT INTO "by_language" VALUES('browser-text','misc','shell and Nickle');
INSERT INTO "by_language" VALUES('exam-macros','misc','m4 and LaTeX');
INSERT INTO "by_language" VALUES('page-mode','misc','Emacs lisp');
INSERT INTO "by_language" VALUES('skirmish','misc','Python');
INSERT INTO "by_language" VALUES('uothesis','misc','LaTeX');
CREATE TABLE languages(num INT, name VARCHAR(30), desc VARCHAR(100));
INSERT INTO "languages" VALUES(1,'c','C and C++');
INSERT INTO "languages" VALUES(2,'haskell','Haskell');
INSERT INTO "languages" VALUES(3,'java','Java');
INSERT INTO "languages" VALUES(4,'shell','Shell Scripts');
INSERT INTO "languages" VALUES(5,'misc','Misc');
COMMIT;
