#!/bin/bash
# Copyright © 2010 Bart Massey
# Rebuild the forge index pages
PGM="`basename $0`"

if [ -f forge.conf ]
then
    . forge.conf
    if cd "$FORGEPATH" >/dev/null 2>&1
    then
	:
    else
	echo "$PGM: Bad FORGEPATH $FORGEPATH" >&2
	exit 1
    fi
elif [ ! -f forge.db ]
then
    echo "$PGM: Must be run from the TinyForge or ikiwiki directory" >&2
    exit 1
fi

function db {
    sqlite3 -list -separator "$1" "forge.db" "$2"
}

function onebullet {
    NAME="$1"
    VISNAME="$2"
    ATTRIB="$3"
    LANGDETAIL="$4"
    if [ "$NAME" = "$VISNAME" ]
    then
	echo -n "[[$NAME]]"
    else
	echo -n "[[$VISNAME|$NAME]]"
    fi
    if [ "$LANGDETAIL" != "" ]
    then
	echo -n " ($LANGDETAIL)"
    fi
    if [ "$ATTRIB" != "" ]
    then
	echo -n " &mdash; $ATTRIB"
    fi
    echo ""
}


function bullet {
    while read INFO
    do
	echo "$INFO" |
	( IFS='@' read NAME VISNAME ATTRIB
	  echo -n "  * "
	  onebullet "$NAME" "$VISNAME" "$ATTRIB" )
    done
}

function langbullet {
    while read INFO
    do
	echo "$INFO" |
	( IFS='@' read NAME VISNAME ATTRIB LANGDETAIL
	  echo -n "  * "
	  onebullet "$NAME" "$VISNAME" "$ATTRIB" "$LANGDETAIL" )
    done
}

function datebullet {
    while read INFO
    do
	echo "$INFO" |
	( IFS='@' read NAME VISNAME ATTRIB DATE
	  echo -n "  * $DATE "
	  onebullet "$NAME" "$VISNAME" "$ATTRIB" "" )
    done
}

# generate language index
( echo "# Bartforge Index by Programming Language"
  echo ""
  db ' ' "select name, desc from languages order by num;" |
  while read LANG DESC
  do
      echo "$DESC"
      echo ""
      db '@' "select intname, visname, attrib, langdetail from master where language = '$LANG' order by intname;" |
      langbullet
      echo ""
  done ) >language_index.mdwn

# generate alpha index
( echo "# Bartforge Alphabetical Index"
  echo ""
  db '@' "select intname, visname, attrib from master order by intname;" |
  bullet ) >alpha_index.mdwn

# generate date index
( echo "# Bartforge Date Index"
  echo ""
  db '@' "select intname, visname, attrib, adddate from master order by adddate desc;" |
  datebullet ) >date_index.mdwn

# generate master index
( cat index-top.mdwn
  echo ""
  db ' ' "select name, desc from categories order by num;" |
  while read CAT DESC
  do
      echo "$DESC"
      echo ""
      db '@' "select intname, visname, attrib from master where category = '$CAT' order by intname;" |
      bullet
      echo ""
  done ) >index.mdwn
