BEGIN TRANSACTION;
CREATE TABLE categories(num INT PRIMARY KEY, name VARCHAR(30), desc VARCHAR(100));
CREATE TABLE "master"(intname VARCHAR(30) PRIMARY KEY, category VARCHAR(30), visname VARCHAR(30), attrib VARCHAR(100), language VARCHAR(30), langdetail VARCHAR(100), adddate DATE NOT NULL DEFAULT(CURRENT_DATE));
CREATE TABLE languages(num INT PRIMARY KEY, name VARCHAR(30), desc VARCHAR(100));
COMMIT;
